from terraform to bootstrap script

diff --git a/.github/workflows/housekeeping-github.yml b/.github/workflows/housekeeping-github.yml
--- a/.github/workflows/housekeeping-github.yml
+++ b/.github/workflows/housekeeping-github.yml
@@ -1,99 +1,99 @@
----
-name: "Housekeeping: Global Github Configuration"
+# ---
+# name: "Housekeeping: Global Github Configuration"
 
-on:
-  push:
-    branches:
-      - main
-    paths:
-      - .github/workflows/housekeeping-github.yml
-      - src/main/github-config
-  schedule:
-    - cron: '0 6 * * 1' # https://crontab.guru
-  workflow_dispatch:
+# on:
+#   push:
+#     branches:
+#       - main
+#     paths:
+#       - .github/workflows/housekeeping-github.yml
+#       - src/main/github-config
+#   schedule:
+#     - cron: '0 6 * * 1' # https://crontab.guru
+#   workflow_dispatch:
 
-permissions:
-  contents: write
-  issues: write
+# permissions:
+#   contents: write
+#   issues: write
 
-jobs:
-  lint-terraform:
-    name: Lint Terraform config
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Debug
-        run: pwd && ls -alF
-      - name: tflint
-        run: |
-          (
-            cd src/main/github-config || exit
-            ./apply-config.sh lint
-          )
-        shell: bash
+# jobs:
+#   lint-terraform:
+#     name: Lint Terraform config
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+#       - name: Debug
+#         run: pwd && ls -alF
+#       - name: tflint
+#         run: |
+#           (
+#             cd src/main/github-config || exit
+#             ./apply-config.sh lint
+#           )
+#         shell: bash
 
-  apply-github-config:
-    name: Apply config by running Terraform
-    runs-on: ubuntu-latest
-    needs: lint-terraform
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: initialize
-        run: |
-          (
-            cd src/main/github-config || exit
-            ./apply-config.sh init
-          )
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        shell: bash
-      - name: Checkout repo which contains the terraform state file
-        uses: actions/checkout@v3
-        with:
-          repository: sommerfeld-io/dev-environment-config
-          token: ${{ secrets.TERRAFORM }}
-          path: target/tmp/repos/dev-environment-config
-      - name: validate
-        run: |
-          (
-            cd src/main/github-config || exit
-            ./apply-config.sh validate
-          )
-        shell: bash
-      - name: plan
-        run: |
-          (
-            cd src/main/github-config || exit
-            ./apply-config.sh plan ${{ secrets.TERRAFORM }} ${{ secrets.BW_CLIENT_ID }} ${{ secrets.BW_CLIENT_SECRET }} ${{ secrets.BW_MASTER_PASS }}
-          )
-        shell: bash
-      - name: apply
-        run: |
-          (
-            cd src/main/github-config || exit
-            ./apply-config.sh apply ${{ secrets.TERRAFORM }} ${{ secrets.BW_CLIENT_ID }} ${{ secrets.BW_CLIENT_SECRET }} ${{ secrets.BW_MASTER_PASS }}
-          )
-        shell: bash
-      - name: ALWAYS cleanup
-        if: always()
-        run: |
-          (
-            cd src/main/github-config || exit
-            ./apply-config.sh cleanup
-          )
-        shell: bash
+#   apply-github-config:
+#     name: Apply config by running Terraform
+#     runs-on: ubuntu-latest
+#     needs: lint-terraform
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+#       - name: initialize
+#         run: |
+#           (
+#             cd src/main/github-config || exit
+#             ./apply-config.sh init
+#           )
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#         shell: bash
+#       - name: Checkout repo which contains the terraform state file
+#         uses: actions/checkout@v3
+#         with:
+#           repository: sommerfeld-io/dev-environment-config
+#           token: ${{ secrets.TERRAFORM }}
+#           path: target/tmp/repos/dev-environment-config
+#       - name: validate
+#         run: |
+#           (
+#             cd src/main/github-config || exit
+#             ./apply-config.sh validate
+#           )
+#         shell: bash
+#       - name: plan
+#         run: |
+#           (
+#             cd src/main/github-config || exit
+#             ./apply-config.sh plan ${{ secrets.TERRAFORM }} ${{ secrets.BW_CLIENT_ID }} ${{ secrets.BW_CLIENT_SECRET }} ${{ secrets.BW_MASTER_PASS }}
+#           )
+#         shell: bash
+#       - name: apply
+#         run: |
+#           (
+#             cd src/main/github-config || exit
+#             ./apply-config.sh apply ${{ secrets.TERRAFORM }} ${{ secrets.BW_CLIENT_ID }} ${{ secrets.BW_CLIENT_SECRET }} ${{ secrets.BW_MASTER_PASS }}
+#           )
+#         shell: bash
+#       - name: ALWAYS cleanup
+#         if: always()
+#         run: |
+#           (
+#             cd src/main/github-config || exit
+#             ./apply-config.sh cleanup
+#           )
+#         shell: bash
 
-  on-failure:
-    runs-on: ubuntu-latest
-    needs: ['lint-terraform', 'apply-github-config']
-    if: failure()
-    steps:
-      - name: Send Pipeline Status to Google Chat
-        if: always()
-        uses: Co-qn/google-chat-notification@releases/v1
-        with:
-          name: ${{ github.workflow }}
-          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
-          status: failure
+#   on-failure:
+#     runs-on: ubuntu-latest
+#     needs: ['lint-terraform', 'apply-github-config']
+#     if: failure()
+#     steps:
+#       - name: Send Pipeline Status to Google Chat
+#         if: always()
+#         uses: Co-qn/google-chat-notification@releases/v1
+#         with:
+#           name: ${{ github.workflow }}
+#           url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
+#           status: failure
